name:                bot-main
version:             0.1.0.0
github:              "githubuser/bot-main"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bot-main#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- aeson
- filepath
- time
- http-conduit
- http-client
- http-client-tls
- http-types
- text
- conduit
- conduit-extra
- uri-encode
- yaml
- directory

library:
  source-dirs:           src

executables:
  bot-main-exe:
    main:                Main.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot-main

tests:
  bot-main-test:
    main:                Spec.hs
    other-modules:       []
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot-main
